services:
  server:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_NAME: "postgres"
      DB_HOSTNAME: "database"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
    develop:
      watch:
        - action: rebuild
          path: main.go
        - action: rebuild
          path: ./internal/
  database:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local
